name: Security Scan - Trivy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run Trivy scan on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: my-app:latest
          format: table
          severity: CRITICAL,HIGH
          vuln-type: os,library
          exit-code: 1
        continue-on-error: true

      - name: Run Synk container scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: my-app:latest
          args: --severity-threshold=high

